[package]
name = "flat"
version = "0.1.0"
edition = "2021"

[lib]
name = "flat"
crate-type = ["staticlib", "cdylib"]

[dependencies]
jni = { version = "0.21.1", optional = true, default-features = false }

[features]
default = ["jni"]
